#
# Makefile for tegra ...
#

subdir-ccflags-y = -Werror

# start of strict-aliasing fix
CFLAGS_hier_ictlr.o = -fno-strict-aliasing
CFLAGS_hier_ictlr_sysfs.o = -fno-strict-aliasing

obj-y += hier_ictlr.o
obj-y += hier_ictlr_sysfs.o

